# Exercise 2: numpy

In [8]:
import numpy as np

## Problem 1: 

Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **matrix** objects

In [1]:
################
# your solution
################

A = np.matrix([[3,2,1],[6,-3,0],[1,2,9]])
B = np.matrix([[-4,1],[7,3],[2,5]])
C = A*B

print(C)

[[  4  14]
 [-45  -3]
 [ 28  52]]


Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **array** objects

In [4]:
D = np.array(A)
E = np.array(B)
F = A@B

print(F)

[[  4  14]
 [-45  -3]
 [ 28  52]]


In [11]:
 # bit-wise product
D*D

array([[ 9,  4,  1],
       [36,  9,  0],
       [ 1,  4, 81]])

In [12]:
# (psb) Use arrays. Most libraries use (including numpy) array.
# Actual matrix multiplication
D@E

array([[  4,  14],
       [-45,  -3],
       [ 28,  52]])

In [16]:
D

array([[ 3,  2,  1],
       [ 6, -3,  0],
       [ 1,  2,  9]])

In [17]:
D[1]

array([ 6, -3,  0])

In [18]:
D[:,0]

array([3, 6, 1])

## Problem 2: 

Numpy provides random number generators for different distributions.
You can find simple examples at [https://numpy.org/doc/stable/reference/random/index.html](https://numpy.org/doc/stable/reference/random/index.html)

1. Write a function that outputs a list of 250 numbers in a normal distribution with (approximately) mean of 2.5 and standard deviation of 0.75. (check [https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal))
2. Write a loop that uses this function to create 10 instances of such lists. Compute the actual mean and standard deviation and print them.
3. Verify that the answers are indeed random by running your code multiple times.

In [19]:
################
# your solution
################

def getList():
    return np.random.normal(2.5, 0.75, 2500)

for i in range(10):
    data = getList()
    print(f"avg={np.mean(data):16.8f}, std={np.std(data):16.8f}")


avg=      2.48006119, std=      0.74817171
avg=      2.51375607, std=      0.74835199
avg=      2.47989535, std=      0.76260310
avg=      2.46770501, std=      0.73242813
avg=      2.49934493, std=      0.74113899
avg=      2.50501921, std=      0.71953765
avg=      2.50378282, std=      0.74823268
avg=      2.49613439, std=      0.76625419
avg=      2.49089876, std=      0.75693837
avg=      2.51552777, std=      0.76884290


## Problem 3: 

1. Compute and print the eigenvalues, $\lambda_i$, and eigenvectors, ${\bf n}_i$, of
$$
   {\bf A} =
   \left[ \begin{array}{ccccc}
   3 & 2 & 1 & 0 & 0 \\
   2 & 3 & 2 & 1 & 0 \\
   1 & 2 & 3 & 2 & 1 \\
   0 & 1 & 2 & 3 & 2 \\
   0 & 0 & 1 & 2 & 3 
   \end{array} \right]
$$
2. Show that
$$
   {\rm det}({\bf A}) = \prod_{i=1}^5 \lambda_i
$$
3. Verify the following relation
$$
   {\bf A} = \sum_{i=1}^{5} \lambda_i\,{\bf n}_i\otimes{\bf n}_i
$$

In [34]:
################
# your solution
################

# 1.
A = np.array([
    [3,2,1,0,0],
    [2,3,2,1,0],
    [1,2,3,2,1],
    [0,1,2,3,2],
    [0,0,1,2,3]
])

(eigVal, eigVec) = np.linalg.eig(A)

for i in range(5):
        lambda_i = eigVal[i]
        nu_i = eigVec[:, i]
        print(f"lambda={lambda_i:f} with eigen vector ={nu_i}")
        
# 2.
d = 1
for x in eigVal:
    d *= x
    
print(40*'=')
print(np.linalg.det(A), d)

# if (np.linalg.det(A) == d):
#     print("they are equal")
# else:
#     print(f"they are NOT equal:\ndiff = {diff} relative diff = {relDiff}")
   
diff = np.linalg.det(A) - d
relDiff = diff / d

if (np.abs(relDiff) < 1.e-12):
    print("they are equal")
    


# 3.
B = np.zeros((5, 5))
for i in range(5):
    nu_i = eigVec[:, i]
    B += eigVal[i] * np.outer(nu_i, nu_i)
    
print(40*'=')
print(np.linalg.norm(A), np.linalg.norm(B), np.linalg.norm(A-B))


lambda=7.654273 with eigen vector =[0.3287337  0.48567647 0.55866362 0.48567647 0.3287337 ]
lambda=4.561553 with eigen vector =[ 5.57345410e-01  4.35162146e-01 -4.52590146e-16 -4.35162146e-01
 -5.57345410e-01]
lambda=1.747703 with eigen vector =[ 0.61754841 -0.17829779 -0.41675859 -0.17829779  0.61754841]
lambda=0.438447 with eigen vector =[ 4.35162146e-01 -5.57345410e-01 -1.44647414e-15  5.57345410e-01
 -4.35162146e-01]
lambda=0.598024 with eigen vector =[ 0.10280135 -0.48200442  0.71708245 -0.48200442  0.10280135]
16.000000000000007 15.999999999999991
they are NOT equal:
diff = 1.5987211554602254e-14 relative diff = 9.992007221626415e-16
9.1104335791443 9.1104335791443 1.3803842561048463e-14
